use_frameworks!

target 'cocoaPodsTestLibrary_Example' do
  pod 'cocoaPodsTestLibrary', :path => '../'

  target 'cocoaPodsTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
